{{/*
Copyright (c) 2018-present, Facebook, Inc.
All rights reserved.

This source code is licensed under the BSD-style license found in the
LICENSE file in the root directory of this source tree. An additional grant
of patent rights can be found in the PATENTS file in the same directory.
*/}}

{{/*
Fluentd daemonset goes in {{ .Release.Namespace }} namespace to have multiple fluentd in the same cluster
due to the system-node-critical priority class
*/}}
{{- if .Values.fluentd_daemon.create }}
{{- $serviceName := "orc8r-fluentd-daemon" -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd-daemon
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: fluentd-daemon
    addonmanager.kubernetes.io/mode: Reconcile
---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentd-daemon
  labels:
    k8s-app: fluentd-daemon
    addonmanager.kubernetes.io/mode: Reconcile
rules:
- apiGroups:
  - ""
  resources:
  - "namespaces"
  - "pods"
  verbs:
  - "get"
  - "watch"
  - "list"
---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentd-daemon
  labels:
    k8s-app: fluentd-daemon
    addonmanager.kubernetes.io/mode: Reconcile
subjects:
- kind: ServiceAccount
  name: fluentd-daemon
  namespace: {{ .Release.Namespace }}
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: fluentd-daemon
  apiGroup: ""
---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ $serviceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: fluentd-daemon
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: fluentd-daemon
  template:
    metadata:
      labels:
        k8s-app: fluentd-daemon
        app.kubernetes.io/component: fluentd-daemon
    spec:
      priorityClassName: system-node-critical
      serviceAccountName: fluentd-daemon

      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml . | trimSuffix "\n" | indent 8}}
      {{- end }}

      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule

      containers:
        - name: fluentd-daemon
          image: {{ required "fluentd_daemon.image.repository must be provided" .Values.fluentd_daemon.image.repository }}:{{ .Values.fluentd_daemon.image.tag }}
          env:
            - name:  FLUENT_ELASTICSEARCH_HOST
              value: {{ .Values.fluentd_daemon.env.elastic_host | quote }}
            - name:  FLUENT_ELASTICSEARCH_PORT
              value: {{ .Values.fluentd_daemon.env.elastic_port | quote }}
            - name: FLUENT_ELASTICSEARCH_SCHEME
              value: {{ .Values.fluentd_daemon.env.elastic_scheme | quote }}
          resources:
{{ toYaml .Values.fluentd_daemon.resources | indent 12 }}
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: config-volume
              mountPath: /fluentd/etc

      terminationGracePeriodSeconds: 30

      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: config-volume
          configMap:
            name: orc8r-fluentd-es-configs
{{- end}}
